
export const products = [
   {
      name: 'Пепперони',
      categoryId: 1,
      imagePath: 'storage/public/images/products/Пепперони.png',
      descriptionShort: 'Пикантная пепперони, увеличенная порция моцареллы, томаты, фирменный томатный соус',
      priceDefault: 699,
   },
   {
      name: 'Баварская',
      categoryId: 1,
      imagePath: 'storage/public/images/products/Баварская.png',
      descriptionShort: 'Бекон, митболы, моцарелла, томаты, шампиньоны, сладкий перец, красный лук, чеснок, фирменный томатный соус',
      priceDefault: 799,
   },
   {
      name: 'Мясная',
      categoryId: 1,
      imagePath: 'storage/public/images/products/Мясная.png',
      descriptionShort: 'Мортаделла, соус песто, моцарелла, кубики брынзы и фирменный томатный соус',
      priceDefault: 899,
   },
   {
      name: 'Вегетарианская',
      categoryId: 1,
      imagePath: 'storage/public/images/products/Вегетарианская.png',
      descriptionShort: 'Шампиньоны, ароматный грибной соус, лук, сухой чеснок, моцарелла, смесь сыров чеддер и пармезан, фирменный соус альфредо',
      priceDefault: 599,
   },
   {
      name: 'Грибная',
      categoryId: 1,
      imagePath: 'storage/public/images/products/Грибная.png',
      descriptionShort: 'Шампиньоны, ароматный грибной соус, лук, сухой чеснок, моцарелла, смесь сыров чеддер и пармезан',
      priceDefault: 649,
   },
   {
      name: 'Чоризо',
      categoryId: 1,
      imagePath: 'storage/public/images/products/Чоризо.png',
      descriptionShort: 'Острые колбаски чоризо, сладкий перец, моцарелла, фирменный томатный соус',
      priceDefault: 749,
   },
   {
      name: 'Сытная',
      categoryId: 1,
      imagePath: 'storage/public/images/products/Сытная.png',
      descriptionShort: 'Шампиньоны, томаты, сладкий перец, красный лук, кубики брынзы, моцарелла',
      priceDefault: 899,
   },
   {
      name: 'Сэндвич с ветчиной',
      categoryId: 2,
      imagePath: 'storage/public/images/products/Сэндвич с ветчиной.png',
      descriptionShort: 'Знакомое сочетание ветчины, цыпленка, моцареллы со свежими томатами, соусом и чесноком',
      priceDefault: 349,
   },
   {
      name: 'Сэндвич по домашнему 2 шт.',
      categoryId: 2,
      imagePath: 'storage/public/images/products/Сэндвич по домашнему 2 шт..png',
      descriptionShort: 'Ветчина, сыр, зелень и помидоры в свежем тосте',
      priceDefault: 199,
   },
   {
      name: 'Картофель фри',
      categoryId: 2,
      imagePath: 'storage/public/images/products/Картофель фри.png',
      descriptionShort: 'Вкуснейшая картошка фри, 150г.',
      priceDefault: 149,
   },
   {
      name: 'Нагетсы с картошкой фри',
      categoryId: 2,
      imagePath: 'storage/public/images/products/Нагетсы с картошкой фри.png',
      descriptionShort: 'Нежное куриное мясо в хрустящей панировке с картошечкой',
      priceDefault: 499,
   },
   {
      name: 'Салат Цезарь',
      categoryId: 2,
      imagePath: 'storage/public/images/products/Салат Цезарь.png',
      descriptionShort: 'Цыпленок, свежие листья салата, сыры чеддер и пармезан, соус цезарь, пшеничные гренки, итальянские травы',
      priceDefault: 299,
   },
   {
      name: 'Цезарь-ролл',
      categoryId: 2,
      imagePath: 'storage/public/images/products/Цезарь-ролл.png',
      descriptionShort: 'Куриное мясо в хрустящей панировке, ломтик помидора, листья салата и ломтики сыра, заправленные специальным соусом и завёрнутые в пшеничную лепешку',
      priceDefault: 249,
   },
   {
      name: 'Чизкейк шоколадный',
      categoryId: 3,
      imagePath: 'storage/public/images/products/Чизкейк шоколадный.png',
      descriptionShort: 'Нежный сырно-творожный десерт на основе толченого печенья',
      priceDefault: 199,
   },
   {
      name: 'Капкейк нежный',
      categoryId: 3,
      imagePath: 'storage/public/images/products/Капкейк нежный.png',
      descriptionShort: 'Домашний капкейк, приготовленный с любовью',
      priceDefault: 149,
   },
   {
      name: 'Пирожное Радость',
      categoryId: 3,
      imagePath: 'storage/public/images/products/Пирожное Радость.png',
      descriptionShort: 'Нежный бисквит в заварном креме с ягодами',
      priceDefault: 299,
   },
   {
      name: 'Латте',
      categoryId: 4,
      imagePath: 'storage/public/images/products/Латте.png',
      descriptionShort: 'Классический латте с нежной молочной пенкой',
      priceDefault: 149,
   },
   {
      name: 'Капучино',
      categoryId: 4,
      imagePath: 'storage/public/images/products/Капучино.png',
      descriptionShort: 'Для любителей сбалансированного кофейно-молочного вкуса',
      priceDefault: 149,
   },
   {
      name: 'Американо',
      categoryId: 4,
      imagePath: 'storage/public/images/products/Американо.png',
      descriptionShort: 'Идеальный горячий напиток, раскрывает глубокий, богатый вкус эспрессо с более легкой консистенцией',
      priceDefault: 149,
   },
   {
      name: 'Макиато',
      categoryId: 4,
      imagePath: 'storage/public/images/products/Макиато.png',
      descriptionShort: 'Кофейный напиток, изготавливаемый из порции эспрессо и небольшого количества молока',
      priceDefault: 149,
   },
   {
      name: 'Добрый кола',
      categoryId: 5,
      imagePath: 'storage/public/images/products/Добрый кола.png',
      descriptionShort: 'Освежающий напиток, 0.5л',
      priceDefault: 99,
   },
   {
      name: 'Добрый апельсин',
      categoryId: 5,
      imagePath: 'storage/public/images/products/Добрый апельсин.png',
      descriptionShort: 'Вкус свежего апельсина, 0.5л',
      priceDefault: 99,
   },
   {
      name: 'Чесночный соус',
      categoryId: 6,
      imagePath: 'storage/public/images/products/Чесночный соус.png',
      descriptionShort: 'Фирменный соус с чесночным вкусом, 25г',
      priceDefault: 49,
   },
   {
      name: 'Васаби',
      categoryId: 6,
      imagePath: 'storage/public/images/products/Васаби.png',
      descriptionShort: 'Острый васаби, 25г',
      priceDefault: 49,
   },
   {
      name: 'Кетчуп',
      categoryId: 6,
      imagePath: 'storage/public/images/products/Кетчуп.png',
      descriptionShort: 'Вкусный кетчуп, 25г',
      priceDefault: 49,
   },
   {
      name: 'Колпак',
      categoryId: 7,
      imagePath: 'storage/public/images/products/Колпак.png',
      descriptionShort: 'Праздничный колпак, 4шт',
      priceDefault: 149,
   },
]

