import { ROLE } from '#constants/api/v1/roles.js'

export const roles = [
   {
      id: ROLE.SUPER_ADMIN.ID,
      name: ROLE.SUPER_ADMIN.NAME,
      description: ROLE.SUPER_ADMIN.DESCRIPTION
   },
   {
      id: ROLE.DIRECTOR_GENERAL.ID,
      name: ROLE.DIRECTOR_GENERAL.NAME,
      description: ROLE.DIRECTOR_GENERAL.DESCRIPTION
   },
   {
      id: ROLE.DEPUTY_GENERAL_DIRECTOR.ID,
      name: ROLE.DEPUTY_GENERAL_DIRECTOR.NAME,
      description: ROLE.DEPUTY_GENERAL_DIRECTOR.DESCRIPTION
   },
   {
      id: ROLE.ADMINISTRATOR_GENERAL.ID,
      name: ROLE.ADMINISTRATOR_GENERAL.NAME,
      description: ROLE.ADMINISTRATOR_GENERAL.DESCRIPTION
   },
   {
      id: ROLE.DIRECTOR_RESTAURANT.ID,
      name: ROLE.DIRECTOR_RESTAURANT.NAME,
      description: ROLE.DIRECTOR_RESTAURANT.DESCRIPTION
   },
   {
      id: ROLE.DEPUTY_DIRECTOR_RESTAURANT.ID,
      name: ROLE.DEPUTY_DIRECTOR_RESTAURANT.NAME,
      description: ROLE.DEPUTY_DIRECTOR_RESTAURANT.DESCRIPTION
   },
   {
      id: ROLE.ADMINISTRATOR_RESTAURANT.ID,
      name: ROLE.ADMINISTRATOR_RESTAURANT.NAME,
      description: ROLE.ADMINISTRATOR_RESTAURANT.DESCRIPTION
   },
   {
      id: ROLE.COURIER.ID,
      name: ROLE.COURIER.NAME,
      description: ROLE.COURIER.DESCRIPTION
   }
]