import { ROLE } from "#constants/api/v1/roles.js"

export const PERMISSIONS = Object.freeze({
   GENERAL: [
      ROLE.DIRECTOR_GENERAL,
      ROLE.DEPUTY_GENERAL_DIRECTOR,
      ROLE.ADMINISTRATOR_GENERAL],

   SECONDARY: [
      ROLE.DIRECTOR_RESTAURANT,
      ROLE.DEPUTY_DIRECTOR_RESTAURANT,
      ROLE.ADMINISTRATOR_RESTAURANT],

})