import {
   EMPLOYEES_ROUTE_PERMISSIONS,
   ADDRESSES_ROUTE_PERMISSIONS,
   COUNTRIES_ROUTE_PERMISSIONS,
   CITIES_ROUTE_PERMISSIONS,
   RESTAURANT_SCHEDULES_ROUTE_PERMISSIONS,
   RESTAURANTS_ROUTE_PERMISSIONS,
   DELIVERY_ZONES_ROUTE_PERMISSIONS,
   CATEGORIES_ROUTE_PERMISSIONS,
   PRODUCTS_ROUTE_PERMISSIONS,
   PRODUCT_RESTAURANTS_ROUTE_PERMISSIONS,
   ORDERS_ROUTE_PERMISSIONS,
} from './modelsRoutePermissions.js'

export const ALL_ROUTE_PERMISSIONS = [
   ...Object.values(EMPLOYEES_ROUTE_PERMISSIONS),
   ...Object.values(ADDRESSES_ROUTE_PERMISSIONS),
   ...Object.values(COUNTRIES_ROUTE_PERMISSIONS),
   ...Object.values(CITIES_ROUTE_PERMISSIONS),
   ...Object.values(RESTAURANT_SCHEDULES_ROUTE_PERMISSIONS),
   ...Object.values(RESTAURANTS_ROUTE_PERMISSIONS),
   ...Object.values(DELIVERY_ZONES_ROUTE_PERMISSIONS),
   ...Object.values(CATEGORIES_ROUTE_PERMISSIONS),
   ...Object.values(PRODUCTS_ROUTE_PERMISSIONS),
   ...Object.values(PRODUCT_RESTAURANTS_ROUTE_PERMISSIONS),
   ...Object.values(ORDERS_ROUTE_PERMISSIONS),
]