@host=https://api.demopizza.ru/api/v1
# @host=http://localhost:5000/api/v1

### алгоритм работы авторизации
// 1. Пользователь заходит на страницу входа
// 2. Фронтенд отправляет запрос на получение уникальной ссылки (authTgBotLoginLink) 
//    Ссылка действительна 5 минут

GET {{host}}/auth/telegram-bot/get-login-link

// 3. Фронтенд отрисовыввает кнопку "войти с помощью телеграмм", 
//    для мониторов необходимо также сделать QR-код для ссылки (import QrcodeVue from 'qrcode.vue')
// 4. При нажатии на кнопку вызывается событие window.open(authTgBotLoginLink)
// 5. Пользователь попадает в телеграм бот, предназначенный для подтверждения номера телефона 
//    и подтверждает его
// 6. Для того чтобы фронтенду понять, подтвержден ли номер телефона, фронтенд делает polling на 
//    auth/telegram-bot/check-login-link. Лучше организовать polling для проверки 
//    сразу после получения ссылки для входа в интервале 3-5 сек. И завершить polling после успешного
//    ответа или выхода со страницы login

###
POST {{host}}/auth/telegram-bot/check-login-link

// 7. После подтверждения номера телефона в тг боте, запрос вернет "status": "verified"
// 8. Если статус verified, то можно отправить пустой запрос на login
###
POST {{host}}/auth/login

// 9. При успешной авторизации auth/login установит JWT токены в куки и вернет данные пользователя.
//    Для тестов accessToken действует 30 секунд, refreshToken 2 минуты 
// 10. Для обновления accessToken
###
POST {{host}}/auth/refresh

// 11. Logout
###
DELETE {{host}}/auth/logout

// 12. Для теста пока есть только 1 защищенный роут, возвращает пользователя если он авторизован
###
GET {{host}}/auth/user