# @host=https://api.demopizza.ru/api/v1
@host=http://localhost:5000/api/v1

###  доступные query параметры для GET запросов 
###  include: ['country'],
###  sort: ['id', 'name', 'createdAt', 'updatedAt'] asc по умолчанию, desc надо прописывать

GET {{host}}/cities
###

GET {{host}}/cities?include=country&sort=name,desc

###
GET {{host}}/cities/1

###
POST {{host}}/cities
content-type: application/json

{
   "name": "Пермь2",
   "countryId": 1,
   //iframe код карты для отображения зон доставки на сайте (клиент будет делать с помощью яндекс карт)
   //необязательный параметр
   "mapIframe": "<iframe></iframe>" 
}

###
PUT {{host}}/cities/2
content-type: application/json

{
   "name": "Пермь New",
   "countryId": 1,
   //iframe код карты для отображения зон доставки на сайте (клиент будет делать с помощью яндекс карт)
   //необязательный параметр
   "mapIframe": "<iframe></iframe>"
}

###
DELETE {{host}}/cities/2

