@host=https://api.demopizza.ru/api/v1
# @host=http://localhost:5000/api/v1

###  доступные query параметры для GET запросов 
###  include: ['cities'],
###  sort: ['id', 'name', 'createdAt', 'updatedAt'] asc по умолчанию, desc надо прописывать

GET {{host}}/countries
###

GET {{host}}/countries?include=cities&sort=name,desc

###
GET {{host}}/countries/1

###
POST {{host}}/countries
content-type: application/json

{
   "name": "Узбекистан"
}

###
PUT {{host}}/countries/4
content-type: application/json

{
   "name": "Узбекистан New"
}

###
DELETE {{host}}/countries/2

