@host=https://api.demopizza.ru/api/v1
# @host=http://localhost:5000/api/v1

###  доступные query параметры для GET запросов 
###  sort: ['id', 'phone', 'email', 'lastName', 'createdAt', 'updatedAt']

GET {{host}}/employees
###

GET {{host}}/employees?sort=phone,desc

###
GET {{host}}/employees/1


###
POST {{host}}/employees
content-type: application/json

{
   "phone": "+79129416435",

   // все параметры ниже необязательные
   "email": "test@test.ru",
   "firstName": "Иван",
   "lastName": "Иванов",
   "middleName": "Иванович",
   //должность
   "jobTitle": "Администратор",

   "employeeRoles": [
      {
         "roleId": 4,
         "restaurantId": 1
      },
      {
         "roleId": 5,
         "restaurantId": 1
      }
   ]
}

###
PUT {{host}}/employees/3
content-type: application/json

{
   "phone": "+79129416435",

   // все параметры ниже необязательные
   "email": "test@test.ru",
   "firstName": "Иван",
   "lastName": "Иванов",
   "middleName": "Иванович",
   //название должности
   "jobTitle": "Администратор",

   "employeeRoles": [
      {
         "roleId": 4,
         "restaurantId": 1
      },
      {
         "roleId": 5,
         "restaurantId": 1
      }
   ]
}

###
DELETE {{host}}/employees/3