# @host=https://api.demopizza.ru/api/v1
@host=http://localhost:5000/api/v1

GET {{host}}/legal-documents

###
GET {{host}}/legal-documents/2

###
POST {{host}}/legal-documents
content-type: application/json

{
   "name": "Политика конфиденциальности",

   // docFile - необязательный параметр, можно добавить через form-data в postman
   "docFile": null, 

   // link - необязательный параметр, ссылка на документ, если он расположен на стороннем ресурсе,
   // например в гугл докс
   "link": null, 

   // htmlContent - необязательный параметр, сделал если захотим сделать редактор документа прям на странице,
   // для убоного отображения на сайте, по сути пока не нужен т.к. файл или ссылку легче и удобнее сделать
   "htmlContent": null, 

   // description - необязательный параметр, краткое описание
   "description": null, 

   // isActive - показывать/не показывать документ на сайте
   "isActive": true 
}

###
PUT {{host}}/legal-documents/4
content-type: application/json

{
    "name": "Политика конфиденциальности",

   // docFile - необязательный параметр, можно добавить через form-data в postman
   "docFile": null, 

   // link - необязательный параметр, ссылка на документ, если он расположен на стороннем ресурсе,
   // например в гугл докс
   "link": "ссылка", 

   // htmlContent - необязательный параметр, сделал если захотим сделать редактор документа прям на странице,
   // для убоного отображения на сайте, по сути пока не нужен т.к. файл или ссылку легче и удобнее сделать
   "htmlContent": "теги", 

   // description - необязательный параметр, краткое описание
   "description": "описание",

   // isActive - показывать/не показывать документ на сайте
   "isActive": false 
}

###
DELETE {{host}}/legal-documents/2

