# @host=https://api.demopizza.ru/api/v1
@host=http://localhost:5000/api/v1

###  доступные query параметры для GET запросов 
###  include: ['cities'],
###  sort: ['id', 'name', 'createdAt', 'updatedAt'] asc по умолчанию, desc надо прописывать

GET {{host}}/products
###

GET {{host}}/products?include=category,productRestaurants

###
GET {{host}}/products/1

