-- AlterTable
ALTER TABLE "public"."products" ALTER COLUMN "proteins" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "fats" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "carbohydrates" SET DATA TYPE DOUBLE PRECISION;
